# Generated by Django 3.2.4 on 2021-06-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('areaManager', models.CharField(max_length=100)),
                ('designType', models.CharField(choices=[('platdak', 'Platdak'), ('gen4', 'Gen 4'), ('wind', 'Wind Net')], max_length=30)),
                ('sections', models.IntegerField(default=1)),
                ('lowMaintananceCheck', models.BooleanField(blank=True, default=True)),
                ('folderUrl', models.URLField()),
                ('infoUrl', models.URLField()),
            ],
        ),
    ]
