# Generated by Django 3.2.4 on 2021-06-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageProjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockArea', models.IntegerField(default=1)),
                ('blockOmtrek', models.IntegerField(default=1)),
                ('blockLengte', models.IntegerField(default=1)),
                ('blockBreedte', models.IntegerField(default=1)),
                ('blockRy', models.IntegerField(default=1)),
                ('blockDwars', models.IntegerField(default=1)),
                ('blockHoeke', models.IntegerField(default=1)),
                ('blockHeight', models.IntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageProjects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageProjects.measurement')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageProjects.project')),
            ],
        ),
    ]
