# Generated by Django 3.2.4 on 2021-06-07 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageProjects', '0002_measurement_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='manageProjects.project'),
        ),
    ]
