# Generated by Django 3.2.4 on 2021-06-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageProjects', '0004_auto_20210607_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='project',
            field=models.ManyToManyField(through='manageProjects.Section', to='manageProjects.Project'),
        ),
    ]
