# Generated by Django 3.2.4 on 2021-06-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageProjects', '0005_measurement_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='project',
        ),
    ]
